@BASE_URL=http://localhost:8080/newsletter

###
GET {{BASE_URL}}/subscriptions?page=1&maxPageSize=5 HTTP/1.1

###
POST {{BASE_URL}}/subscriptions HTTP/1.1
content-type: application/json

{
    "blogId": "f05ef3ee-e322-4e7d-be17-5ecb9937f23e",
    "interests": [
        "tech"
    ],
    "userId": "78cc2a9f-ea13-4325-b4d6-5c2a351ba5f8"
}

###
GET {{BASE_URL}}/subscriptions?page=1&maxPageSize=5 HTTP/1.1

###
GET {{BASE_URL}}/subscriptions HTTP/1.1